management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: mongo
  health:
    mongo:
      enabled: true

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://Cluster37916:ynsk0603@Cluster37916.genytgw.mongodb.net/}
      database: ${MONGO_DATABASE:pallete}
  redis:
    redisson:
      config: |
        masterSlaveServersConfig:
          timeout: 3000
          password: null
          readMode: "SLAVE"
          subscriptionMode: "SLAVE"
          slaveAddresses:
            - "redis://127.0.0.1:6379"
          masterAddress: "redis://127.0.0.1:6379"
          database: 0

server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

armeria:
  http2-max-header-list-size: 100000
  http1-max-header-size: 100000
  ports:
    - port: 8080
      protocol: HTTP

grpc:
  docs:
    enabled: true

logging:
  level:
    root: debug
