spring:
  security:
    user:
      name: admin
      password: qwe123!
  application:
    name: pallete-auth
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pallete_auth
    username: root
    password: groot13@
    hikari:
      poolName: Hikari
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 300000
      maximum-pool-size: 10
      minimum-idle: 10
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        connection:
          provider_disables_autocommit: true
        show_sql: false
        dialect: org.hibernate.dialect.MySQL5Dialect
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
